### ISSUE TITLE
🚀 FEAT: Add new transit line

### ISSUE THREAD

**Issue by e-lo** [network-wrangler/projectcard#13]
As a user, I'd like to be able to add a new transit line using a project card.

Please vote on options listed in below comments by indicating 
👍 in options you are **OK** with; 
👎 on options you would **veto**; and 
🚀 on your **favorite** option.

| **Option** | **Pros** | **Cons**
| ----------- | -------- | --------|
| [Option A](#option-a): cube-like | Explicit about where in shape board/alight/dwell time/traveltime modifiers are added. More concise.  How wrangler is set up now. | Has funky minus signs. If just applying a dwell time or board/alight restriction can be overly lengthy and potentially prone to error | 
| [Option A-1](#option-a-1): nest stop parameters under routing | Explicit about where in shape board/alight/dwell time/traveltime modifiers are added. No minus signs. |   Not what is currently implemented.  | 
| [Option B](#option-B): separate stop specification w/ attributes nested under stop  |  More concise if just applying stop-attribute modifiers; no minus signs.  Separates concept of shape and stops. |  Could be prone to errors if have to specify nodes more than once (if not done programmatically). |
| [Option C](#option-C): Emme-like specification with stops nested under attributes.  | Works with Emme. Very explicit. | Since  there are not a lot of a-priori assumptions, it is very lengthy.  |

### Option A

```yml
add_new_route:
  routes:
    - route_id: abc
      route_long_name: green_line
      route_short_name: green
      route_type: 3
      agency_raw_name: MTr
      agency_id: 1
      trips:
        - direction_id: 0
          headway_sec: 
             - ['6:00','12:00']: 600
             - ['12:00','13:00']: 900
          routing:
           - 1
           --2
           --3
           - node_id: 4
              board: 1
              exit: 0
           --5
           -6
        - direction_id: 1
          headway_sec: 
             - ['6:00','12:00']: 600
             - ['12:00','13:00']: 900
          routing:
           - 6
           - node_id: 5
             dwell: 30
           - 4
           - - 6
           - 3
              ttime_to_next_node: 90
           - 2
           - 1
     
```

### Option A-1

```yml
add_new_route:
  routes:
    - route_id: abc
      route_long_name: green_line
      route_short_name: green
      route_type: 3
      agency_raw_name: MTr
      agency_id: 1
      trips:
        - direction_id: 0
          headway_sec: 
             - ('6:00','12:00'): 600
             - ('12:00','13:00'): 900
          routing:
           -1:
               stop: True #when stop is set to True, defaults to allow both boarding and alighting
           -2
           -3
           -4: 
               stop: True # default to False, specify only when stopping
               alight: False  # default to True, specify only when not default
           -5
           -6:
               stop: True
        - direction_id: 1
          headway_sec: 
             - ('6:00','12:00'): 600
             - ('12:00','13:00'): 900
          routing:
           -6:
               stop: True
           -5:
               stop: True
               dwell_sec: 30
           -4:
               stop: True
           -6
           -3:
               time_to_next_node_sec: 90
           -2:
               stop: True
           -1:
               stop: True
     
```
    
### Option B

Separate stop and routing specifications. With attributes nested under stops. 

```yml
add_new_route:
  routes:
    - route_id: abc
      route_long_name: green_line
      route_short_name: green
      route_type: 3
      agency_raw_name: MTr
      agency_id: 1
      trips:
        - direction_id: 0
          headway_sec: 
             - ['6:00','12:00']: 600
             - ['12:00','13:00']: 900
          shape:
           -1
           -2
           -3
           -node_id: 4
            time_to_next_nodes: 90
           -5
           -6
          stops: #an assumption that boarding and alighting are allowed at each stop unless otherwise specified.
           - 1
           - node_id: 4
              board: 1
              exit: 0
           -6
        - direction_id: 1
          headway_sec: 
             - ['6:00','12:00']: 600
             - ['12:00','13:00']: 900
          shape:
           - 6
           - 5
           - 4
           - 6
           - 3
           - 2
           - 1
           stops:
           - 6.1 # noting that this ONLY applies to the first 6; otherwise assumed to apply to all 6s
           - 5
           - 4
           - node_id: 3
             dwell_time: 90 # could specify under routing b/c sometimes dwells occur at layovers.
           - 2
           - 1
 ```

### Option C

Emme-like; nests nodes under attributes.

```yml
add_new_route:
  routes:
    - route_id: abc
      route_long_name: green_line
      route_short_name: green
      route_type: 3
      agency_raw_name: MTr
      agency_id: 1
      trips:
        - direction_id: 0
          headway_sec: 
             - ['6:00','12:00']: 600
             - ['12:00','13:00']: 900
          shape: #could still be called routing...if we consolidated to a single way of doing this in property changes as well.
           -1
           -2
           -3
           -4
           -5
           -6
          allow_boarding: #default: not allow/not stop
           -1
           -4
           -6
          allow_alighting:  #default: not allow/not stop
           -1
           -6
        - direction_id: 1
          headway_sec: 
             - ['6:00','12:00']: 600
             - ['12:00','13:00']: 900
          shape:
           - 6
           - 5
           - 4
           - 6
           - 3
           - 2
           - 1
           allow_boarding:
           - 6.1 # noting that this ONLY applies to the first 6; otherwise assumed to apply to all 6s
           - 5
           - 4
           - 3
           - 2
           - 1
           allow_alighting:
           - 6.1 # noting that this ONLY applies to the first 6; otherwise assumed to apply to all 6s
           - 5
           - 4
           - 3
           - 2
           - 1
           dwell_time:
           3: 90
           time_between_nodes:  
              from: 5
              to: 4
              time: 80
 ```

**Comment by e-lo** [comment]
Notes from mtg with Met Council:

1. Note-level features are not currently used by MetCouncil and so if this adds complexity/cot then it is not a priority.
2. Specifying shapes/stops:
    - Dave doesn't like routing being within trips and would prefer a separate shapes and stops specification. He will put his thoughts in this issue.
    - Elizabeth pointed out that this would add a redundancy that would require consistency (and thus be prone to errors)
    - Rachel stated that she does do a lot of manual editing of transit cards and ideally wouldn't have to change routing in two places within the same card.

**Comment by DavidOry** [comment]
I think the goal here is to have a specification that:

1. Is easy for Met Council and other users to read and manipulate, as needed.
2. Communicates with the broader world as logical, understandable. 

I think conflating the `shape` and `stops` ideas, to use GTFS's terminology, is confusing. And the syntax in the above spec is unattractive, with the negative symbol. 

I would prefer something like:
 
``` yaml
add_new_transit:
  routes:
    - route_id: abc
      route_long_name: green_line
      route_short_name: green
      route_type: 3
      agency_name: MTr
      is_agency_new: False
   - trips:
      trip_id: 123
      direction_id: 0   
      - frequency:
         timespan: ['6:00','12:00']
         headway_secs: 60
      - shape:
         - 1
         - 2
         - 3
         - 4
       - stops:
          - 2
          - 4: 
             board: True
             exit: False
     trip_id: 124
     direction: 1
     - frequency:
       timespan: ['6:00','12:00']
       headway_secs: 60
     - shape:
        - 4
        - 3
        - 2
        - 1
     - stops: 
        - 4
        - 2
     
```

A few notes:

1. We shouldn't use 'agency_raw_name'. Let's ask for the `agency` name and understand if it's new or existing.
2. The unit here, the thing we are adding is a `route`. Or at least I think it should be. So why not nest things under route? I think this would be easier to understand than a long list of trips that you then need to cross reference to your route.  Is it easier this way to keep the schema clean? Or is the idea that every new route will have a separate `add_new_transit` key?
3. Separating the `shape` and the `stops` could cause some redundancy. But I like seeing the stops separate. If not, then perhaps label it `shape_and_stops` and then use something more YAML'y to denote a stop. Perhaps:

```yaml
  - shape_and_stop:
     - 1: stop: True
     - 2: stop: False
```
I do not see the benefit of using a super secret code to denote a stop. 

4. I think it's better to just use `True` and `False` than the `0` and `1`, when possible.

**Comment by e-lo** [comment]
## Option A (Cube-like)

**Comment by e-lo** [comment]
## Option B (Combo)

**Comment by e-lo** [comment]
## Option C (Emme-like)

**Comment by RachelWikenMC** [comment]
My initial reaction is to keep the stops and shape together in a single list, similar to the CUBE format. Then there is only one place to edit if trying to manually update. Dave's suggestion is fairly easy to read, compared to double -- in the first example. 
shape_and_stop:
     - 1: stop: True
     - 2: stop: False
     

I assume like the .lin file, we could have multiple headways/time periods for each trip? the examples above are all single time period. If we have to break them out by time period, manual editing would be difficult and I would probably just do a new .lin file diff instead of any hand editing of 5 time periods 

**example** 
      trips:
        - trip_id: 123
          direction_id: 0
          headway_secs: 60
          **timespan: ['6:00','12:00'] 
                           [12-3] for example 
                           [3-7]**

**Comment by e-lo** [comment]
> the examples above are all single time period.
@RachelWikenMC  - Good catch!  I've updated the examples to have a nested structure of time period ranges to headways.  Open to suggestions about other methods to incorporate this flexibility.

**Comment by e-lo** [comment]
> My initial reaction is to keep the stops and shape together in a single list, similar to the CUBE format. Then there is only one place to edit if trying to manually update. Dave's suggestion is fairly easy to read, compared to double -- in the first example.
shape_and_stop:
- 1: stop: True
- 2: stop: False

Taking that direction, I added another option, Option 1-A.  What do you think?

**Comment by e-lo** [comment]
### Option 1-A

**Comment by i-am-sijia** [comment]
@RachelWikenMC good catch indeed!
>  I've updated the examples to have a nested structure of time period ranges to headways.

@e-lo trips are specific to time period. I wouldn't nest the time periods under the same trip record. In the example case, wrangler needs to add four records to trips with four unique trip_id, and four records to frequencies.

**Comment by e-lo** [comment]
> wrangler needs to add four records to trips with four unique trip_id, and four records to frequencies.

Wrangler can still do that under the hood though, right? I just don't want to have to make @RachelWikenMC create multiple copies of same trip shape.

**Comment by i-am-sijia** [comment]
> > wrangler needs to add four records to trips with four unique trip_id, and four records to frequencies.
> 
> Wrangler can still do that under the hood though, right? I just don't want to have to make @RachelWikenMC create multiple copies of same trip shape.

Right, no need for copies of shape. I was suggesting we change to:

```yaml
add_new_route:
  routes:
    - route_id: abc
      route_long_name: green_line
      route_short_name: green
      route_type: 3
      agency_raw_name: MTr
      agency_id: 1
      trips:
        - direction_id: 0
          headway_sec: 
             - ['6:00','12:00']: 600
               trip_id: 1231 # Lasso can generate unique trip_id
             - ['12:00','13:00']: 900
               trip_id: 1232 # Lasso can generate unique trip_id
          routing:
           - 1
           --2
           --3
           - node_id: 4
              board: 1
              exit: 0
           --5
           -6
        - direction_id: 1
          headway_sec: 
             - ['6:00','12:00']: 600
               trip_id: 1241 # Lasso can generate unique trip_id
             - ['12:00','13:00']: 900
               trip_id: 1242 # Lasso can generate unique trip_id
          routing:
           - 6
           - node_id: 5
             dwell: 30
           - 4
           - - 6
           - 3
              ttime_to_next_node: 90
           - 2
           - 1
```

**Comment by RachelWikenMC** [comment]
> ### Option 1-A
> 👍: ok 👎: veto 🚀 : my pick
🚀 1-A will work. Can we combine that with Sijia's time period example above? 

This might just be weird formatting on github, but the Node ID and the stop info are not on the same line. Is it possible to make it one row? the new line is making it hard to read for me. 

Also if possible, could stop false be assumed and only stop: true be required? It would make it much easier to pick out the stop pattern when reviewing. Open to others' thoughts on that.  We aren't using dwell, time specifics, or exit only stops right now, so I would just have a big list of true and false. Would be easier to read if it was just True 
       routing:
           - 6: 
           - 5: stop: True
           - 4:  stop: True
           - 6:
           - 3: 
           - 2:  stop: True
           - 1:  stop: True

**Comment by i-am-sijia** [comment]
We have edited option A-1 based on Rachel's feedback. Option A-1 is now the more preferred option. We will finalize this once we talk to MTC tomorrow. @lmz

**Comment by lmz** [comment]
I voted - I like Option 1-A as well.

Noting that in the long run, it would be nice to have nodes (in the add node/add link process) have their names work as aliases and so this file would become something that non-modelers could give us (like project sponsors).

**Comment by e-lo** [comment]
So after writing up an example, I realized that we 

1. cannot have (in `yaml` and in basically every language) repeated node_id's if they are the keys/hashes/lookup values.

❌ 
```yaml
routing:
   1: 
   2:
   3:
   1:  # This is invalid 
```

2. we cannot guarantee the ordering of **objects** once they are translated to things like a python dictionary.  Therefore

```yaml
routing:
   1: 
   2:
   3:
```

**Could** end up as:

```python
{"routing": {1: ..., 3:..., 2:...}
```

### Potential Solution

- Use list of objects.  Lists retain order.
- Put node_id within the object so if we need to repeat them they aren't conflicting.

*downsides*: this is more verbose.

```yaml
routing:
    - node_id: 6
      stop: True
    - node_id:5:
      stop: True
      dwell_sec: 30
    - node_id: 4
      stop: True
    - node_id: 6
    - node_id: 3
      time_to_next_node_sec: 90
    - node_id: 2
      stop: True
    - node_id: 1
      stop: True
```

Thoughts? @i-am-sijia @RachelWikenMC @lmz @DavidOry

**Comment by RachelWikenMC** [comment]
I don't have a strong opinion. I need something that works. The example above is not super easy to read quickly, but as long as it would be automatically created from a diff of .lin files, it would be ok

**Comment by i-am-sijia** [comment]
@e-lo we adopted option A-1. `routing` is already a list, not a dictionary. For example, below is a new transit line project card @yueshuaing generated for Met Council:

```yaml
project: 
tags: ''
dependencies: ''
changes:
- category: Add New Route
  routes:
  - route_id: abc
    route_short_name: green_line
    route_long_name: green
    route_type: 3
    agency_raw_name: metro_transit_10_27_23
    agency_id: 0
    trips:
    - direction_id: 0
      headway_sec:
      - ('6:00', '10:00'): 600
      - ('10:00', '15:00'): 900
      routing:
      - 16505:
          stop: true
      - 196629
      - 11089
      - 11234:
          stop: true
      - 18129
      - 31280:
          stop: true
    - direction_id: 1
      headway_sec:
      - ('6:00', '10:00'): 600
      - ('10:00', '15:00'): 900
      routing:
      - 31280:
          stop: true
      - 18129:
          stop: true
      - 11234:
          stop: true
      - 21260
      - 11234:
          stop: true
      - 11089
      - 196629:
          stop: true
      - 16505:
          stop: true
```
@e-lo I don't think the things you raised concerns us. Let me know if I'm missing anything.
