### ISSUE TITLE
Update Schema to respond to dependencies in validation

### ISSUE THREAD

**Issue by e-lo** [network-wrangler/projectcard#3]
*As a project card user, I'd like to have useful error messages when my project card is invalid so that I can easily fix it*

## Issue

Until now, the project card spec has used a relatively flat structure for specifying changes. Each change was bundled into a single object with minimal nesting as such:

```yml
project: my project
..
..
category: roadway deletion
links:
 model_link_id: [123,123,123]
nodes:
 model_node_id: [432,432,432]
```

The main issue with this approach is that when the card is validated, we don't know *at the outset* which sub-schema to apply for each respective change type (deletion, addition, transit, etc) and thus it needs to get matched for each of them using the [`oneOf` key in json-schema.](https://json-schema.org/understanding-json-schema/reference/combining.html#oneof) 

While this technically works, it provides extremely unhelpful error messages as it will show you an error in matching the sub-schema to a (seemingly random) one of the `oneOf` subschemas (i.e. showing why a roadway deletion project didn't match a managed lane project) rather than explaining why some minutiae of your roadway deletion project didn't work for roadway deletion.  This can be extremely frustrating. 

## Proposed Solution

In order to make the sub-schema validation conditional on the sub-schema type, we need to provide a key in an upper-level of the schema.  As such, I propose the following as a starting point:

```yml
project: my project
..
..
roadway_deletion:   #<----this becomes a key rather than a value; and more importantly is at an upper level.
  links:
   model_link_id: [123,123,123]
  nodes:
   model_node_id: [432,432,432]
```

This works well when having multiple changes as well:
```yml
project: my project
..
..
changes:
  - roadway_deletion:  
     links:
       model_link_id: [123,123,123]
     nodes:
       model_node_id: [432,432,432]
  - roadway_addition:  
     ...
```

There are also application benefits when applied to network wrangler as one doesn't have to dive *into* the change in order to know what kind we have, we can just query the changes keys.

### 1. This is a breaking change

**Proposed Remedies:** 
 
- add schema versions to project cards for easier validation of multiple versions in the future
- add a conversion script to the project card repo
- NetworkWrangler 1.0 should accept either version (should be easy to *sniff* because of "category" key)

### 2. Is there anything else we'd like to change while we are breaking things?

**Suggestions:**

- removing unnecessary nesting of objects as lists when there is just one (i.e. `A` doesn't need to have a list of `osm_node_id`s
- changing roadway segment selection keywords `A` and `B` (which are used as link values) to `from` and `to`
- changing the `properties` keyword to `property_changes` to facilitate disambiguation with the json-schema `properties` which also appears in the error traces for validation errors
- Undo unnecessary nesting of `facility`:`links`:`model_link_id` (and similar) and instead `facility`: `model_link_id`

What else @i-am-sijia @lmz @JonathanEhrlichMC othrs?
