### ISSUE TITLE
🚀 [FEAT] Add project card change type for deleting transit service

### ISSUE THREAD

**Issue by e-lo** [network-wrangler/projectcard#30]
As a user who wants to delete service, I'd like to create project cards which selects trips based on existing trip selection features and deletes them. I want to optionally clean associated shapes and routes records if they aren't being used by other trips.

```yaml
project: Remove AM service on the Green Line
transit_service_deletion:
  service:
    trip_properties:
      route_short_name: "green"
    timespans:
      - ['06:00:00', '09:00:00']
  clean_shapes: false
  clean_routes: false
```
