### ISSUE TITLE
🚀  FEAT: Align spec for transit routing change features to new route

### ISSUE THREAD

**Issue by e-lo** [network-wrangler/projectcard#35]
*As a user coding changes to transit stop permissions, dwell times, or hard coded transit travel times, I'd like to be able to code these as a transit routing change rather than having to delete the route and then re-add it as a new route*

## The way it is

Transit routing changes currently only have the ability to turn a stop on/off. Note that as currently specified in the spec it is a [generic array](https://github.com/network-wrangler/projectcard/blob/main/projectcard/schema/changes/transit_routing_change.json), so *could* have more information, but it isn't built in to a specific representation.

```yaml
transit_routing_change:
  service:...
  routing:
    existing:
     - 1
     - 2
     - 3
    set:
      - 1
      - -2
      - 3
```

Whereas [new routes can specify](https://github.com/network-wrangler/projectcard/blob/dc470fdc153fa361661a9bd3f88bb2d6d831934d/projectcard/schema/transit/transit_routing.json#L21):

- `boarding`: bool
- `alighting`: bool
- `stop`: bool
- `time_to_next_node_sec`: int
- `dwell_sec`: int

```yaml
transit_route_addition:
  routes:
    - route_id: ...
      trips:
          headway_secs: ...
          routing:
            - 1:
                stop: true #when stop is set to True, defaults to allow both boarding and alighting
            - 2
            - 3:
                time_to_next_node_sec: 90
            - 4:
                stop: true # default to False, specify only when stopping
                alight: false  # default to True, specify only when not default
            - 5
```
## Existing work-arounds

You can work-around this limitation by deleting a route and then re-adding it back in, although this would create different trip_ids.

## The way it could be

```yaml
transit_routing_change:
  service:...
  routing:
    existing:
     - 1
     - 2
     - 3
    set:
            - 1:
                stop: true #when stop is set to True, defaults to allow both boarding and alighting
            - 2
            - 3:
                time_to_next_node_sec: 90
```
